//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneClickZip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneClickZip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One_Click_Zip_Designer.
        /// </summary>
        internal static string APPLICATION_ID {
            get {
                return ResourceManager.GetString("APPLICATION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_24px {
            get {
                object obj = ResourceManager.GetObject("clear_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CREATOR_DETAILS {
            get {
                object obj = ResourceManager.GetObject("CREATOR_DETAILS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_24px {
            get {
                object obj = ResourceManager.GetObject("delete_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .oczb.
        /// </summary>
        internal static string FILE_BATCH_ONE_CLICK_EXTENSION_NAME {
            get {
                return ResourceManager.GetString("FILE_BATCH_ONE_CLICK_EXTENSION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Zip Batch File Executor.
        /// </summary>
        internal static string FILE_BATCH_ONE_CLICK_EXTENSION_NAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("FILE_BATCH_ONE_CLICK_EXTENSION_NAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Zip Batch File|*.oczb.
        /// </summary>
        internal static string FILE_BATCH_ONE_CLICK_FILTER_NAME {
            get {
                return ResourceManager.GetString("FILE_BATCH_ONE_CLICK_FILTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .oczd.
        /// </summary>
        internal static string FILE_DESIGNER_EXTENSION_NAME {
            get {
                return ResourceManager.GetString("FILE_DESIGNER_EXTENSION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Zip Project Designer.
        /// </summary>
        internal static string FILE_DESIGNER_EXTENSION_NAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("FILE_DESIGNER_EXTENSION_NAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Click Zip Designer|*.oczd.
        /// </summary>
        internal static string FILE_DESIGNER_FILTER_NAME {
            get {
                return ResourceManager.GetString("FILE_DESIGNER_FILTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_Plus_16px {
            get {
                object obj = ResourceManager.GetObject("folder_Plus_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_Plus_24px {
            get {
                object obj = ResourceManager.GetObject("folder_Plus_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_Plus_32px1 {
            get {
                object obj = ResourceManager.GetObject("folder Plus 32px1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_Plus_512px {
            get {
                object obj = ResourceManager.GetObject("folder_Plus_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo-icon-batch-64px.ico.
        /// </summary>
        internal static string ICON_FOR_PROJECT_BATCH_FILE {
            get {
                return ResourceManager.GetString("ICON_FOR_PROJECT_BATCH_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo-icon-64px.ico.
        /// </summary>
        internal static string ICON_FOR_PROJECT_DESIGNER_FILE {
            get {
                return ResourceManager.GetString("ICON_FOR_PROJECT_DESIGNER_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_icon_128px {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_128px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_icon_16px {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_16px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_icon_20px {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_20px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_icon_256px {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_256px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_icon_32px {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_32px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_icon_512px {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo_icon_64px {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_64px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Logo_icon_64px1 {
            get {
                object obj = ResourceManager.GetObject("Logo_icon_64px1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlusMinus_24px {
            get {
                object obj = ResourceManager.GetObject("PlusMinus_24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
